var svgMapDataActive = {

    data: {
      newcases: {
        name: 'New Cases',
        thousandSeparator: ','
      },

      totaldeaths: {
        name: 'Total Deaths',
        thousandSeparator: ','
      },

      newdeaths: {
        name: 'New Deaths',
        thousandSeparator: ','
      },

      totalcases: {
        name: 'Total Cases',
        thousandSeparator: ','
      },

      totalrecovered: {
        name: 'Total Recovered',
        thousandSeparator: ','
      },

      criticalcases: {
        name: 'Critical Cases',
        thousandSeparator: ','
      },

      activecases: {
        name: 'Active Cases',
        format: '{0}',
        thousandSeparator: ',',
        thresholdMax: 280,
        thresholdMin: 20
      }
    },
    applyData: 'activecases',

    values: {
AF: {totalcases: 4, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 4, totalrecovered: 0.0, criticalcases: 0.0},
AL: {totalcases: 2, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 0.0},
DZ: {totalcases: 20, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 20, totalrecovered: 0.0, criticalcases: 0.0},
AD: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
AR: {totalcases: 12, newcases: 0, totaldeaths: 1.0, newdeaths: 0.0, activecases: 11, totalrecovered: 0.0, criticalcases: 0.0},
AM: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
AU: {totalcases: 93, newcases: +10, totaldeaths: 3.0, newdeaths: 0.0, activecases: 68, totalrecovered: 22.0, criticalcases: 1.0},
AT: {totalcases: 131, newcases: +27, totaldeaths: 0.0, newdeaths: 0.0, activecases: 129, totalrecovered: 2.0, criticalcases: 1.0},
AZ: {totalcases: 9, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 9, totalrecovered: 0.0, criticalcases: 0.0},
BH: {totalcases: 109, newcases: +24, totaldeaths: 0.0, newdeaths: 0.0, activecases: 87, totalrecovered: 22.0, criticalcases: 0.0},
BD: {totalcases: 3, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 3, totalrecovered: 0.0, criticalcases: 0.0},
BY: {totalcases: 6, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 6, totalrecovered: 0.0, criticalcases: 0.0},
BE: {totalcases: 239, newcases: +39, totaldeaths: 0.0, newdeaths: 0.0, activecases: 238, totalrecovered: 1.0, criticalcases: 1.0},
BT: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
BA: {totalcases: 5, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 0.0, criticalcases: 0.0},
BR: {totalcases: 25, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 25, totalrecovered: 0.0, criticalcases: 1.0},
BG: {totalcases: 4, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 4, totalrecovered: 0.0, criticalcases: 0.0},
KH: {totalcases: 2, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 1.0, criticalcases: 0.0},
CM: {totalcases: 2, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 0.0},
CA: {totalcases: 77, newcases: +11, totaldeaths: 1.0, newdeaths: 1.0, activecases: 68, totalrecovered: 8.0, criticalcases: 1.0},
CL: {totalcases: 13, newcases: +3, totaldeaths: 0.0, newdeaths: 0.0, activecases: 13, totalrecovered: 0.0, criticalcases: 0.0},
CN: {totalcases: 80739, newcases: +44, totaldeaths: 3120.0, newdeaths: 23.0, activecases: 18877, totalrecovered: 58742.0, criticalcases: 5111.0},
CO: {totalcases: 3, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 3, totalrecovered: 0.0, criticalcases: 0.0},
CR: {totalcases: 9, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 9, totalrecovered: 0.0, criticalcases: 1.0},
HR: {totalcases: 13, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 13, totalrecovered: 0.0, criticalcases: 0.0},
CY: {totalcases: 2, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 0.0},
CZ: {totalcases: 38, newcases: +6, totaldeaths: 0.0, newdeaths: 0.0, activecases: 38, totalrecovered: 0.0, criticalcases: 0.0},
DK: {totalcases: 90, newcases: +55, totaldeaths: 0.0, newdeaths: 0.0, activecases: 89, totalrecovered: 1.0, criticalcases: 0.0},
DO: {totalcases: 5, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 0.0, criticalcases: 0.0},
EC: {totalcases: 15, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 15, totalrecovered: 0.0, criticalcases: 1.0},
EG: {totalcases: 55, newcases: 0, totaldeaths: 1.0, newdeaths: 0.0, activecases: 53, totalrecovered: 1.0, criticalcases: 0.0},
EE: {totalcases: 10, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 10, totalrecovered: 0.0, criticalcases: 0.0},
FI: {totalcases: 33, newcases: +8, totaldeaths: 0.0, newdeaths: 0.0, activecases: 32, totalrecovered: 1.0, criticalcases: 0.0},
FR: {totalcases: 1412, newcases: +203, totaldeaths: 30.0, newdeaths: 11.0, activecases: 1370, totalrecovered: 12.0, criticalcases: 21.0},
GF: {totalcases: 5, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 0.0, criticalcases: 0.0},
GE: {totalcases: 15, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 15, totalrecovered: 0.0, criticalcases: 1.0},
DE: {totalcases: 1191, newcases: +151, totaldeaths: 2.0, newdeaths: 2.0, activecases: 1171, totalrecovered: 18.0, criticalcases: 9.0},
GI: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 0, totalrecovered: 1.0, criticalcases: 0.0},
GR: {totalcases: 84, newcases: +11, totaldeaths: 0.0, newdeaths: 0.0, activecases: 84, totalrecovered: 0.0, criticalcases: 1.0},
HK: {totalcases: 115, newcases: 0, totaldeaths: 3.0, newdeaths: 0.0, activecases: 53, totalrecovered: 59.0, criticalcases: 6.0},
HU: {totalcases: 9, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 9, totalrecovered: 0.0, criticalcases: 0.0},
IS: {totalcases: 65, newcases: +7, totaldeaths: 0.0, newdeaths: 0.0, activecases: 64, totalrecovered: 1.0, criticalcases: 0.0},
IN: {totalcases: 47, newcases: +7, totaldeaths: 0.0, newdeaths: 0.0, activecases: 43, totalrecovered: 4.0, criticalcases: 0.0},
ID: {totalcases: 19, newcases: +13, totaldeaths: 0.0, newdeaths: 0.0, activecases: 19, totalrecovered: 0.0, criticalcases: 0.0},
IR: {totalcases: 7161, newcases: +595, totaldeaths: 237.0, newdeaths: 43.0, activecases: 4530, totalrecovered: 2394.0, criticalcases: 0.0},
IQ: {totalcases: 71, newcases: +6, totaldeaths: 7.0, newdeaths: 1.0, activecases: 61, totalrecovered: 3.0, criticalcases: 0.0},
IE: {totalcases: 24, newcases: +3, totaldeaths: 0.0, newdeaths: 0.0, activecases: 24, totalrecovered: 0.0, criticalcases: 0.0},
IL: {totalcases: 50, newcases: +11, totaldeaths: 0.0, newdeaths: 0.0, activecases: 46, totalrecovered: 4.0, criticalcases: 1.0},
IT: {totalcases: 9172, newcases: +1797, totaldeaths: 463.0, newdeaths: 97.0, activecases: 7985, totalrecovered: 724.0, criticalcases: 733.0},
JP: {totalcases: 530, newcases: +28, totaldeaths: 9.0, newdeaths: 2.0, activecases: 420, totalrecovered: 101.0, criticalcases: 33.0},
JO: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
KW: {totalcases: 65, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 64, totalrecovered: 1.0, criticalcases: 3.0},
LV: {totalcases: 6, newcases: +3, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 1.0, criticalcases: 0.0},
LB: {totalcases: 41, newcases: +9, totaldeaths: 0.0, newdeaths: 0.0, activecases: 40, totalrecovered: 1.0, criticalcases: 3.0},
LI: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
LT: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
LU: {totalcases: 5, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 0.0, criticalcases: 0.0},
MY: {totalcases: 117, newcases: +18, totaldeaths: 0.0, newdeaths: 0.0, activecases: 93, totalrecovered: 24.0, criticalcases: 2.0},
MV: {totalcases: 6, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 6, totalrecovered: 0.0, criticalcases: 0.0},
MT: {totalcases: 4, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 4, totalrecovered: 0.0, criticalcases: 0.0},
MQ: {totalcases: 2, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 0.0},
MX: {totalcases: 7, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 6, totalrecovered: 1.0, criticalcases: 1.0},
MD: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
MC: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
MA: {totalcases: 2, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 1.0},
NP: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 0, totalrecovered: 1.0, criticalcases: 0.0},
NL: {totalcases: 321, newcases: +56, totaldeaths: 4.0, newdeaths: 1.0, activecases: 317, totalrecovered: 0.0, criticalcases: 1.0},
NZ: {totalcases: 5, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 0.0, criticalcases: 0.0},
NG: {totalcases: 2, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 0.0},
NO: {totalcases: 224, newcases: +48, totaldeaths: 0.0, newdeaths: 0.0, activecases: 223, totalrecovered: 1.0, criticalcases: 0.0},
OM: {totalcases: 18, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 9, totalrecovered: 9.0, criticalcases: 0.0},
PK: {totalcases: 16, newcases: +9, totaldeaths: 0.0, newdeaths: 0.0, activecases: 15, totalrecovered: 1.0, criticalcases: 0.0},
PS: {totalcases: 25, newcases: +6, totaldeaths: 0.0, newdeaths: 0.0, activecases: 25, totalrecovered: 0.0, criticalcases: 0.0},
PY: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
PE: {totalcases: 9, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 9, totalrecovered: 0.0, criticalcases: 0.0},
PH: {totalcases: 24, newcases: +14, totaldeaths: 1.0, newdeaths: 0.0, activecases: 21, totalrecovered: 2.0, criticalcases: 1.0},
PL: {totalcases: 17, newcases: +6, totaldeaths: 0.0, newdeaths: 0.0, activecases: 17, totalrecovered: 0.0, criticalcases: 2.0},
PT: {totalcases: 39, newcases: +9, totaldeaths: 0.0, newdeaths: 0.0, activecases: 39, totalrecovered: 0.0, criticalcases: 0.0},
QA: {totalcases: 18, newcases: +3, totaldeaths: 0.0, newdeaths: 0.0, activecases: 18, totalrecovered: 0.0, criticalcases: 0.0},
RO: {totalcases: 17, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 12, totalrecovered: 5.0, criticalcases: 0.0},
RU: {totalcases: 20, newcases: +3, totaldeaths: 0.0, newdeaths: 0.0, activecases: 17, totalrecovered: 3.0, criticalcases: 0.0},
SM: {totalcases: 51, newcases: +14, totaldeaths: 2.0, newdeaths: 1.0, activecases: 49, totalrecovered: 0.0, criticalcases: 5.0},
SA: {totalcases: 20, newcases: +9, totaldeaths: 0.0, newdeaths: 0.0, activecases: 19, totalrecovered: 1.0, criticalcases: 0.0},
SN: {totalcases: 4, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 3, totalrecovered: 1.0, criticalcases: 0.0},
RS: {totalcases: 2, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 2, totalrecovered: 0.0, criticalcases: 0.0},
SG: {totalcases: 160, newcases: +10, totaldeaths: 0.0, newdeaths: 0.0, activecases: 67, totalrecovered: 93.0, criticalcases: 10.0},
SK: {totalcases: 7, newcases: +2, totaldeaths: 0.0, newdeaths: 0.0, activecases: 7, totalrecovered: 0.0, criticalcases: 0.0},
SI: {totalcases: 23, newcases: +7, totaldeaths: 0.0, newdeaths: 0.0, activecases: 23, totalrecovered: 0.0, criticalcases: 0.0},
ZA: {totalcases: 7, newcases: +4, totaldeaths: 0.0, newdeaths: 0.0, activecases: 7, totalrecovered: 0.0, criticalcases: 0.0},
KR: {totalcases: 7478, newcases: +165, totaldeaths: 53.0, newdeaths: 3.0, activecases: 7259, totalrecovered: 166.0, criticalcases: 36.0},
ES: {totalcases: 1229, newcases: +555, totaldeaths: 30.0, newdeaths: 13.0, activecases: 1167, totalrecovered: 32.0, criticalcases: 11.0},
LK: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 0, totalrecovered: 1.0, criticalcases: 0.0},
SE: {totalcases: 260, newcases: +57, totaldeaths: 0.0, newdeaths: 0.0, activecases: 259, totalrecovered: 1.0, criticalcases: 0.0},
CH: {totalcases: 374, newcases: +42, totaldeaths: 2.0, newdeaths: 0.0, activecases: 369, totalrecovered: 3.0, criticalcases: 0.0},
TW: {totalcases: 45, newcases: 0, totaldeaths: 1.0, newdeaths: 0.0, activecases: 29, totalrecovered: 15.0, criticalcases: 0.0},
TH: {totalcases: 50, newcases: 0, totaldeaths: 1.0, newdeaths: 0.0, activecases: 16, totalrecovered: 33.0, criticalcases: 1.0},
TG: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
TN: {totalcases: 5, newcases: +3, totaldeaths: 0.0, newdeaths: 0.0, activecases: 5, totalrecovered: 0.0, criticalcases: 0.0},
UA: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
GB: {totalcases: 321, newcases: +43, totaldeaths: 5.0, newdeaths: 2.0, activecases: 298, totalrecovered: 18.0, criticalcases: 0.0},
US: {totalcases: 624, newcases: +83, totaldeaths: 22.0, newdeaths: 0.0, activecases: 587, totalrecovered: 15.0, criticalcases: 8.0},
VA: {totalcases: 1, newcases: 0, totaldeaths: 0.0, newdeaths: 0.0, activecases: 1, totalrecovered: 0.0, criticalcases: 0.0},
VN: {totalcases: 31, newcases: +1, totaldeaths: 0.0, newdeaths: 0.0, activecases: 15, totalrecovered: 16.0, criticalcases: 0.0},
}
 }
